version: '3.1'

services:
  database:
    image: mongo:3.4.4
    ports:
      - 27017:27017
  service:
    build: ./service
    image: colinccook/flapper-news-continued-service
    volumes:
      - ./service:/usr/src/app
      - /usr/src/app/node_modules # https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds
    ports:
      - 3000:3000
    depends_on:
      - database
    secrets:
      - hashkey
  web:
    build: ./web
    image: colinccook/flapper-news-continued-web
    ports:
      - 8090:80
    # volumes:
    #   - ./web:/usr/share/nginx/html
    depends_on:
      - service
secrets:
  hashkey:
    file: ./hashkey